#!/bin/bash
echo "ALX"
^C
root@1d61ade946b2:/alx-pre_course/0x01-git/bash# cat > school
#!/bin/bash
echo "ALX"
root@1d61ade946b2:/alx-pre_course/0x01-git/bash# git add .
root@1d61ade946b2:/alx-pre_course/0x01-git/bash# git commit -m "Starting to code today,so cool"

root@1d61ade946b2:/alx-pre_course/0x01-git#
